# PH 206: Computational Physics  
## Laboratory 06
## Date: 24/02/2026
## Course instructor: Prof. Santabrata Das
## Lab TAs: Tarun Chanda, Rajesh Pramanik, Gaurav Bonde


### Objective
The objective of this laboratory is to introduce students to **Python programming** and its use in **computational physics**.  
This lab focuses on developing familiarity with basic Python syntax, numerical operations, and plotting tools that will be required throughout the course.

### Software and Tools
- Programming Language: **Python**
- Libraries:
  - `NumPy` for numerical computation
  - `Matplotlib` for plotting
- Environment: **Jupyter Notebook (offline mode)**
  
### Installation Instructions
### Setting Up Jupyter Notebook Using Conda

To use **Jupyter Notebook** with Python, it is recommended to install it through **conda**, which provides a reliable and well-maintained environment for scientific computing. You may choose between **Anaconda** or **Miniconda**, depending on your preference.

### Method 1: Using Anaconda (Recommended)

Anaconda is the easiest option for beginners, as it comes with **Jupyter Notebook** and many commonly used scientific Python packages (such as NumPy and Matplotlib) pre-installed.

**Steps to install and launch Jupyter Notebook:**

1. **Download and Install Anaconda**
   - Download the installer from the  **[Official Anaconda Downloads page](https://www.anaconda.com/download)**
   - Follow the installation instructions for your operating system.
     

2. **Launch Jupyter Notebook**
   
   You can start Jupyter Notebook in either of the following ways:

   - **Using Anaconda Navigator (Graphical Interface):**
     - Open the *Anaconda Navigator* application.
     - Click the **Launch** button under *Jupyter Notebook*.

   - **Using the Command Line:**
     - Open **Anaconda Prompt** (Windows) or **Terminal** (macOS/Linux).
     - Run the command:
       ```
       jupyter notebook
       ```
     - A Jupyter Notebook interface will open automatically in your default web browser.

**If you have Anaconda, install **NumPy and Matplotlib** by going to your terminal or command prompt and typing:**
    
    conda install numpy
    conda install matplotlib
    
---

### Instructions
- Internet usage is **strictly prohibited** during the lab session.
- Students must work **individually** on their personal laptops.
- All code must be written during the lab hours.
- The jupyter notebook must be saved with the name **Rollnumber_DDMMYY** format and export the Python file in the **PDF** format before submission. (Replace **Rollnumber** with your Rollnumber and **DDMMYY** with Today's date in the given format. For example: 226112345_160126 ).
- Kindly adhere to the schedule lab timings: 3:00 pm-5:00 pm.
- For any questions or clarifications, please reach out to lab TAs.


In [1]:
##Print your Roll Number and Name
print("ROLL NO: 240121036 \nNAME: om gupta")

ROLL NO: 240121036 
NAME: om gupta



#  Problem: Cubic Spline Approximation

Obtain the **natural cubic spline approximation** for the function defined by:

| x | 0 | 1 | 2 | 3 |
|---|---|---|---|---|
| f(x) | 1 | 2 | 33 | 244 |

Given boundary conditions:

\begin{align}
M(0) &= 0 \\
M(3) &= 0
\end{align}

Estimate:

\begin{align}
f(1.5)
\end{align}

---



#  1. Theory

1. Define **cubic spline interpolation**.
2. Write the general form of a cubic spline in an interval:

\begin{align}
S_i(x) = a_i + b_i(x-x_i) + c_i(x-x_i)^2 + d_i(x-x_i)^3
\end{align}

3. Explain **natural spline boundary conditions**.
4. Derive the system of equations used to compute second derivatives \(M_i\).

---



#  2. Step-by-Step Calculation

## 2.1 Compute Interval Lengths

\begin{align}
h_i = x_{i+1} - x_i
\end{align}

Compute all \(h_i\).

---

## 2.2 Form the System of Equations

Use:

\begin{align}
h_{i-1}M_{i-1} + 2(h_{i-1}+h_i)M_i + h_iM_{i+1}
= 6 \left[ \frac{f_{i+1}-f_i}{h_i} - \frac{f_i-f_{i-1}}{h_{i-1}} \right]
\end{align}

- Write equations for interior nodes.
- Apply boundary conditions.
- Form the complete linear system.

---

## 2.3 Solve for

\begin{align}
M_0, M_1, M_2, M_3
\end{align}

Show all steps clearly.

---



# 🔹 3. Construct Cubic Spline Polynomials

Write spline functions for each interval:

- \( S_0(x) \) for \( 0 \le x \le 1 \)
- \( S_1(x) \) for \( 1 \le x \le 2 \)
- \( S_2(x) \) for \( 2 \le x \le 3 \)

Use the spline formula:

\begin{align}
S_i(x) &= \frac{M_i(x_{i+1}-x)^3}{6h_i}
+ \frac{M_{i+1}(x-x_i)^3}{6h_i} \\
&+ \left(\frac{f_i}{h_i} - \frac{M_i h_i}{6}\right)(x_{i+1}-x)
+ \left(\frac{f_{i+1}}{h_i} - \frac{M_{i+1} h_i}{6}\right)(x-x_i)
\end{align}

---



#  4. Estimate \( f(1.5) \)

- Identify the correct interval.
- Substitute into spline formula.
- Show complete calculation.
- Write final numerical value clearly.

---



#  5. Programming Task

Write a Python program to:

- Construct the system matrix
- Solve for second derivatives
- Evaluate the spline at \( x = 1.5 \)
- Print the final estimated value

---


### You can write your own code here... or... can complete the code snippet given in the cell below.


In [ ]:
import numpy as np
x=[0,1,2,3]
y=[1,2,33,244]
n=4
M=np.zeros(n)

h=1
rhs1 = 6 * (y[2] - 2*y[1] + y[0]) / (h*h)
rhs2 = 6 * (y[3] - 2*y[2] + y[1]) / (h*h)
A = np.array([[4, 1],
              [1, 4]])

B = np.array([rhs1, rhs2])
M1, M2 = np.linalg.solve(A, B)

M[1] = M1
M[2] = M2
z=1.5
def find_interval(x, z):
    for i in range(1, len(x)):
        if x[i-1] <= z <= x[i]:
            return i
    return None


i = find_interval(x, z)
result=(((x[i]-z)**3)*M[i-1]+((z-x[i-1])**3)*M[i])/6*h  +((x[i]-z)*(y[i-1]-((h*h)*M[i-1])/6))/h+((-x[i-1]+z)*(y[i]-((h*h)*M[i])/6))/h
print(M)
print("estimated value",result)


[  0. -24. 276.   0.]
estimated value 1.75
2


In [3]:
import numpy as np

# ============================================================
# Function 1: Construct Natural Cubic Spline
# ============================================================

def natural_cubic_spline(x, y):
    
    # Step 1: Find number of data points
    n = ___________________________      # Write code to get length of x
    
    # Step 2: Compute interval lengths h_i
    h = ___________________________      # Use numpy to compute differences
    
    # Step 3: Create empty matrix A and vector b
    A = ___________________________      # Create zero matrix (n x n)
    b = ___________________________      # Create zero vector (size n)
    
    # --------------------------------------------------------
    # Step 4: Apply Natural Boundary Conditions
    # For natural spline: M0 = 0 and Mn = 0
    # So first and last rows of matrix become:
    # [1 0 0 ... 0]
    # [0 0 0 ... 1]
    # --------------------------------------------------------
    
    A[0,0] = ___________________________
    A[n-1,n-1] = ___________________________
    
    
    # --------------------------------------------------------
    # Step 5: Fill Interior Equations
    # Formula:
    # h[i-1] M[i-1] + 2(h[i-1]+h[i]) M[i] + h[i] M[i+1]
    # = 6[(f[i+1]-f[i])/h[i] - (f[i]-f[i-1])/h[i-1]]
    # --------------------------------------------------------
    
    for i in range(1, ___________________________):
        
        # Fill tridiagonal matrix entries
        
        A[i, i-1] = ___________________________
        A[i, i]   = ___________________________
        A[i, i+1] = ___________________________
        
        # Fill RHS vector b
        b[i] = 6 * ( ___________________________ )
    
    
    # Step 6: Solve linear system A M = b
    M = ___________________________      # Use numpy linear solver
    
    return M



# ============================================================
# Function 2: Evaluate Spline at a Given Value
# ============================================================

def evaluate_spline(x, y, M, value):
    
    # Step 7: Locate correct interval
    for i in range( ___________________________ ):
        
        if x[i] <= value <= x[i+1]:
            
            h = ___________________________
            
            # Compute weights a and b
            a = ___________________________
            b = ___________________________
            
            # Return spline formula
            return (a*y[i] + b*y[i+1] +
                    ((a**3 - a)*M[i] + (b**3 - b)*M[i+1])*(h**2)/6)



# ============================================================
# Main Program
# ============================================================

# Step 8: Define data points
x = np.array([0, 1, 2, 3], dtype=float)
y = np.array([1, 2, 33, 244], dtype=float)

# Step 9: Compute second derivatives
M = ___________________________

print("Second Derivatives:", M)

# Step 10: Evaluate at x = 1.5
value = 1.5
result = ___________________________

print("Estimated f(1.5):", result)

NameError: name '___________________________' is not defined